# Generated by Django 2.0 on 2020-01-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.FloatField()),
                ('status', models.FloatField()),
                ('created', models.DateField()),
            ],
        ),
    ]
