# Generated by Django 2.0 on 2020-01-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
