# Generated by Django 2.0 on 2020-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200104_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='converted_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
