# Generated by Django 2.0 on 2020-01-06 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200104_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
